{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "3db71693",
   "metadata": {},
   "source": [
    "## Unsupervised Clustering Algorithms for Empirical Population Density Based Clusters\n",
    "### Pete Osorio<br>2025-06-04</br>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1d5ce741",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import plotly.io as pio\n",
    "import plotly.figure_factory as ff\n",
    "import plotly.subplots as make_subplots\n",
    "import plotly.graph_objects as go\n",
    "from dash import Dash, dcc, html, Input, Output\n",
    "import rasterio\n",
    "from sklearn.cluster import DBSCAN\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "pio.renderers.default='notebook_connected'\n",
    "pio.templates.default='simple_white'\n",
    "from sklearn.mixture import GaussianMixture\n",
    "from sklearn.neighbors import NearestNeighbors\n",
    "from sklearn.cluster import DBSCAN, KMeans\n",
    "from sklearn.metrics import silhouette_score, silhouette_samples, davies_bouldin_score\n",
    "import math\n",
    "from scipy.spatial.distance import cdist\n",
    "import json\n",
    "from geopy.distance import geodesic"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "021ddb73",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('usa_pd_2020_1km.csv') #retrieved from https://hub.worldpop.org/geodata/summary?id=44771\n",
    "df.rename(columns={'X': 'lon', 'Y': 'lat', 'Z': 'pop'}, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "05edb3fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "bounds_df = pd.read_json('bounds.json') # bounds_df JSON from https://observablehq.com/@rdmurphy/u-s-state-bounding-boxes\n",
    "bounds_df.drop('fips', axis=1, inplace=True)\n",
    "bounds_df.loc[len(bounds_df)] = ['US', [[-171.791110603, 18.91619], [-66.96466, 71.3577635769]]] # US bounding box from https://gist.github.com/graydon/11198540"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e54513fb",
   "metadata": {},
   "source": [
    "# Setup the Dataframe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a8918266",
   "metadata": {},
   "outputs": [],
   "source": [
    "state = 'US'\n",
    "lon_min = bounds_df[bounds_df['state'] == state]['bounds'].values[0][0][0]\n",
    "lon_max = bounds_df[bounds_df['state'] == state]['bounds'].values[0][1][0]\n",
    "lat_min = bounds_df[bounds_df['state'] == state]['bounds'].values[0][0][1]\n",
    "lat_max = bounds_df[bounds_df['state'] == state]['bounds'].values[0][1][1]\n",
    "df_small = df[\n",
    "    (df['pop'].between(50,np.inf)) &\n",
    "    (df['lat'].between(lat_min, lat_max)) &\n",
    "    (df['lon'].between(lon_min, lon_max))\n",
    "    ]\n",
    "max_len = 100000\n",
    "\n",
    "if df_small.shape[0] > max_len:\n",
    "    df_small = df_small.sort_values(by='pop', ascending=False)[:max_len]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2697cdd3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def recalculate_locales(df, bounds_df, state, n_locales, max_len, eps_value, min_samples, min_pop, dbscan_x_include = None):\n",
    "    lon_min = bounds_df[bounds_df['state'] == state]['bounds'].values[0][0][0]\n",
    "    lon_max = bounds_df[bounds_df['state'] == state]['bounds'].values[0][1][0]\n",
    "    lat_min = bounds_df[bounds_df['state'] == state]['bounds'].values[0][0][1]\n",
    "    lat_max = bounds_df[bounds_df['state'] == state]['bounds'].values[0][1][1]\n",
    "    df_small = df[\n",
    "        (df['pop'].between(min_pop,np.inf)) &\n",
    "        (df['lat'].between(lat_min, lat_max)) &\n",
    "        (df['lon'].between(lon_min, lon_max))\n",
    "        ]\n",
    "\n",
    "    if df_small.shape[0] > max_len:\n",
    "        df_small = df_small.sort_values(by='pop', ascending=False)[:max_len]\n",
    "\n",
    "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
    "    df_small['kmeans_labels'] = km.labels_\n",
    "    df_small['kmeans_labels'] = df_small['kmeans_labels'].astype('category')\n",
    "\n",
    "    gmm = GaussianMixture(n_components=n_locales, random_state= 970).fit(df_small[['lat', 'lon']].values)\n",
    "    df_small['gmm_labels'] = gmm.predict(df_small[['lat', 'lon']].values)\n",
    "    df_small['gmm_labels'] = df_small['gmm_labels'].astype('category')\n",
    "\n",
    "    if dbscan_x_include == 'gmm':\n",
    "        X = df_small[['lat', 'lon', 'gmm_labels']].values\n",
    "    elif dbscan_x_include == 'kmeans':\n",
    "        X = df_small[['lat', 'lon', 'kmeans_labels']].values\n",
    "    else:\n",
    "        X = df_small[['lat', 'lon', 'kmeans_labels', 'gmm_labels']].values\n",
    "    X_scaled = StandardScaler().fit_transform(X)\n",
    "    db = DBSCAN(eps=eps_value, min_samples=min_samples, n_jobs=-1).fit(X_scaled)\n",
    "    df_small['dbscan_x_labels'] = np.where(db.labels_ != -1, db.labels_, np.nan)\n",
    "    df_small['dbscan_x_labels'] = df_small['dbscan_x_labels'].astype('category')\n",
    "\n",
    "    X = df_small[['lat', 'lon']].values\n",
    "    X_scaled = StandardScaler().fit_transform(X)\n",
    "    db = DBSCAN(eps=eps_value, min_samples=min_samples, n_jobs=-1).fit(X_scaled)\n",
    "    df_small['dbscan_labels'] = np.where(db.labels_ != -1, db.labels_, np.nan)\n",
    "    df_small['dbscan_labels'] = df_small['dbscan_labels'].astype('category')\n",
    "\n",
    "    return df_small"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c3161d9a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x20be480b7d0>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2025-06-04 22:40:31,628] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 146, in update_polar_plot\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1454, in fit\n",
      "    X = validate_data(\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 2944, in validate_data\n",
      "    out = check_array(X, input_name=\"X\", **check_params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 1130, in check_array\n",
      "    raise ValueError(\n",
      "ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by KMeans.\n",
      "[2025-06-04 22:40:31,638] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 130, in update_cluster_options\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1454, in fit\n",
      "    X = validate_data(\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 2944, in validate_data\n",
      "    out = check_array(X, input_name=\"X\", **check_params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 1130, in check_array\n",
      "    raise ValueError(\n",
      "ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by KMeans.\n",
      "[2025-06-04 22:40:31,644] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 102, in update_map\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1454, in fit\n",
      "    X = validate_data(\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 2944, in validate_data\n",
      "    out = check_array(X, input_name=\"X\", **check_params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 1130, in check_array\n",
      "    raise ValueError(\n",
      "ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by KMeans.\n",
      "[2025-06-04 22:40:41,680] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 146, in update_polar_plot\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1454, in fit\n",
      "    X = validate_data(\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 2944, in validate_data\n",
      "    out = check_array(X, input_name=\"X\", **check_params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 1130, in check_array\n",
      "    raise ValueError(\n",
      "ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by KMeans.\n",
      "[2025-06-04 22:40:41,693] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 130, in update_cluster_options\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1454, in fit\n",
      "    X = validate_data(\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 2944, in validate_data\n",
      "    out = check_array(X, input_name=\"X\", **check_params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 1130, in check_array\n",
      "    raise ValueError(\n",
      "ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by KMeans.\n",
      "[2025-06-04 22:40:41,695] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 102, in update_map\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1454, in fit\n",
      "    X = validate_data(\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 2944, in validate_data\n",
      "    out = check_array(X, input_name=\"X\", **check_params)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 1130, in check_array\n",
      "    raise ValueError(\n",
      "ValueError: Found array with 0 sample(s) (shape=(0, 2)) while a minimum of 1 is required by KMeans.\n",
      "[2025-06-04 23:00:29,613] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 146, in update_polar_plot\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=3 should be >= n_clusters=10.\n",
      "[2025-06-04 23:00:29,619] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 130, in update_cluster_options\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=3 should be >= n_clusters=10.\n",
      "[2025-06-04 23:00:29,627] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 102, in update_map\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=3 should be >= n_clusters=10.\n",
      "[2025-06-04 23:00:34,181] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 130, in update_cluster_options\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=4 should be >= n_clusters=10.\n",
      "[2025-06-04 23:00:34,184] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 102, in update_map\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=4 should be >= n_clusters=10.\n",
      "[2025-06-04 23:00:34,187] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 146, in update_polar_plot\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=4 should be >= n_clusters=10.\n",
      "[2025-06-04 23:01:32,783] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 146, in update_polar_plot\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=4 should be >= n_clusters=10.\n",
      "[2025-06-04 23:01:32,796] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 102, in update_map\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=4 should be >= n_clusters=10.\n",
      "[2025-06-04 23:01:32,809] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 1473, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 882, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 880, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\flask\\app.py\", line 865, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\dash.py\", line 1414, in dispatch\n",
      "    ctx.run(\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 536, in add_context\n",
      "    raise err\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 525, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\dash\\_callback.py\", line 47, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3377057231.py\", line 130, in update_cluster_options\n",
      "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state,\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Pete\\AppData\\Local\\Temp\\ipykernel_28256\\3127680313.py\", line 15, in recalculate_locales\n",
      "    km = KMeans(n_clusters=n_locales, random_state= 970).fit(df_small[['lat', 'lon']])\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\base.py\", line 1389, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1464, in fit\n",
      "    self._check_params_vs_input(X)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 1404, in _check_params_vs_input\n",
      "    super()._check_params_vs_input(X, default_n_init=10)\n",
      "  File \"c:\\Users\\Pete\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sklearn\\cluster\\_kmeans.py\", line 871, in _check_params_vs_input\n",
      "    raise ValueError(\n",
      "ValueError: n_samples=4 should be >= n_clusters=10.\n"
     ]
    }
   ],
   "source": [
    "app = Dash()\n",
    "\n",
    "state_options = [{\"label\": state, \"value\": state} for state in bounds_df[\"state\"].unique()]\n",
    "\n",
    "clusterer_options = {\n",
    "    'K Means': 'kmeans_labels',\n",
    "    'Gaussian Mixture': 'gmm_labels',\n",
    "    'DBSCAN': 'dbscan_labels',\n",
    "    'DBSCAN with Seeds': 'dbscan_x_labels'\n",
    "}\n",
    "\n",
    "seeds_options = {\n",
    "    'K Means': 'kmeans',\n",
    "    'Gaussian Mixture': 'gmm',\n",
    "    'Both': None\n",
    "}\n",
    "\n",
    "md_text = \"\"\"\n",
    "# Unsupervised Clustering Algorithms for Empirical Population Density Based Clusters  \n",
    "Use this applet to find the optimal geographic separation for your sales team, or sports league, or marketing campaign targets!\n",
    "## Dropdown Instructions:  \n",
    "* Use the state dropdownt to select a state or select the entire US.  \n",
    "* Use the cluster quantity dropdown to select the number of clusters you'd like to target. This number is guaranteed for K Means and Gaussian Mixtures, however it's mearly a guideline for DBSCAN with seeds, and it has no effect on DBSCAN.  \n",
    "* Use the algorithm dropdown to select your algorithm. DBSCAN with Seeds will use your seed selection to \"suggest\" clusters for DBSCAN to use.\n",
    "* Use the seed selection dropdown to chose what to seed DBSCAN with Seeds with. You can use either K Means, Gaussian Mixture, or a combination of the two.\n",
    "* Use the slider to select the minimum population (per kilomter) that you'd like to use as a base for your clusters.\n",
    "* Finally, you can use the individual cluster visualizer to see how the cluster is grouped around its geographic center, where the population centers lie, and how large a radius the overal cluster has on a polar plot.\"\"\"\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.Div([\n",
    "        dcc.Markdown(children=md_text)\n",
    "    ]),\n",
    "\n",
    "    html.Div([\n",
    "        dcc.Dropdown(\n",
    "            id='state-dropdown',\n",
    "            options=state_options,\n",
    "            value='US',\n",
    "            placeholder=\"Select a state\",\n",
    "            style={'width': '200px', 'display': 'inline-block', 'margin-right': '10px'}\n",
    "        ),\n",
    "        \n",
    "        dcc.Dropdown(\n",
    "            id='n_locales-dropdown',\n",
    "            options=[{'label': str(i), 'value': i} for i in range(2, 101)],\n",
    "            value=40,\n",
    "            placeholder=\"Select the number of locales\",\n",
    "            style={'width': '200px', 'display': 'inline-block', 'margin-right': '10px'}\n",
    "        ),\n",
    "\n",
    "        dcc.Dropdown(\n",
    "            id='clusterer-dropdown',\n",
    "            options=[{\"label\": k, \"value\": v} for k, v in clusterer_options.items()],\n",
    "            value='dbscan_x_labels',\n",
    "            placeholder=\"Select a clustering algorithm\",\n",
    "            style={'width': '250px', 'display': 'inline-block', 'margin-right': '10px'}\n",
    "        ),\n",
    "\n",
    "        dcc.Dropdown(\n",
    "            id='seeds-dropdown',\n",
    "            options=[{\"label\": k, \"value\": v} for k, v in seeds_options.items()],\n",
    "            value='kmeans',\n",
    "            placeholder=\"Select a seeding algorithm\",\n",
    "            style={'width': '250px', 'display': 'inline-block', 'margin-right': '10px', 'color': '#1E1E1E'}\n",
    "        ),\n",
    "\n",
    "        dcc.Dropdown(\n",
    "            id='cluster-dropdown',\n",
    "            value=0,\n",
    "            placeholder='Select a cluster to visualize',\n",
    "            style={'width': '250px', 'display': 'inline-block'}\n",
    "        ),\n",
    "\n",
    "        html.Div([\n",
    "            dcc.Slider(\n",
    "                id='min-pop-slider',\n",
    "                min=0,\n",
    "                max=5000,\n",
    "                step=10,\n",
    "                value=2500,\n",
    "                marks={i: str(i) for i in range(0, 5001, 500)},\n",
    "                tooltip={\"placement\": \"bottom\", \"always_visible\": True}\n",
    "            )\n",
    "        ], style={'width': '600px', 'margin-top': '20px'})\n",
    "    ], style={'display': 'flex', 'align-items': 'center', 'flex-wrap': 'wrap'}),\n",
    "\n",
    "    html.Div([dcc.Graph(id='map-graph')]),\n",
    "    html.Div([dcc.Graph(id='histogram')]),\n",
    "    html.Div([dcc.Graph(id='polar-plot')]),\n",
    "], style={'backgroundColor': '#1E1E1E', 'color': '#EAEAEA'})\n",
    "\n",
    "@app.callback(\n",
    "    Output('map-graph', 'figure'),\n",
    "    Output('histogram', 'figure'),\n",
    "    Input('state-dropdown', 'value'),\n",
    "    Input('n_locales-dropdown', 'value'),\n",
    "    Input('min-pop-slider', 'value'),\n",
    "    Input('clusterer-dropdown', 'value'),\n",
    "    Input('seeds-dropdown', 'value')\n",
    ")\n",
    "def update_map(selected_state, selected_n_locales, selected_min_pop, selected_clusterer, selected_seeds):\n",
    "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state, \n",
    "                                 n_locales=selected_n_locales, max_len=50000, eps_value=.25, \n",
    "                                 min_samples=30, min_pop=selected_min_pop, dbscan_x_include=selected_seeds)\n",
    "    fig_map = px.scatter_map(df_out,\n",
    "                         lat='lat', lon='lon', color=selected_clusterer,\n",
    "                         hover_data=['pop'], title=f\"The {selected_n_locales} states of {selected_state}\",\n",
    "                         map_style=\"open-street-map\", opacity=0.5, height=1080*.8, width=1920*.8,\n",
    "                         color_discrete_sequence=px.colors.qualitative.Dark24, zoom=4, template='plotly_dark')\n",
    "    df_hist = df_out.groupby(selected_clusterer)['pop'].sum().reset_index()\n",
    "    fig_hist = px.bar(df_hist, x=selected_clusterer, y='pop',\n",
    "                      title=f\"Population Distribution for {selected_clusterer}\",\n",
    "                      labels={selected_clusterer: \"Cluster\", 'pop': \"Total Population\"},\n",
    "                      color=selected_clusterer,\n",
    "                      color_discrete_sequence=px.colors.qualitative.Dark24,\n",
    "                      width=1920*.8,\n",
    "                      template='plotly_dark')\n",
    "\n",
    "    return fig_map, fig_hist\n",
    "\n",
    "@app.callback(\n",
    "    Output('cluster-dropdown', 'options'),\n",
    "    Input('clusterer-dropdown', 'value'),\n",
    "    Input('state-dropdown', 'value'),\n",
    "    Input('n_locales-dropdown', 'value'),\n",
    "    Input('min-pop-slider', 'value'),\n",
    "    Input('seeds-dropdown', 'value')\n",
    ")\n",
    "def update_cluster_options(selected_clusterer, selected_state, selected_n_locales, selected_min_pop, selected_seeds):\n",
    "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state, \n",
    "                                 n_locales=selected_n_locales, max_len=50000, eps_value=.25,\n",
    "                                 min_samples=30, min_pop=selected_min_pop, dbscan_x_include=selected_seeds)\n",
    "    clusters = df_out[selected_clusterer].unique()\n",
    "    return [{\"label\": f\"Cluster {c}\", \"value\": c} for c in clusters]\n",
    "\n",
    "@app.callback(\n",
    "    Output('polar-plot', 'figure'),\n",
    "    Input('cluster-dropdown', 'value'),\n",
    "    Input('clusterer-dropdown', 'value'),\n",
    "    Input('state-dropdown', 'value'),\n",
    "    Input('n_locales-dropdown', 'value'),\n",
    "    Input('min-pop-slider', 'value'),\n",
    "    Input('seeds-dropdown', 'value')\n",
    ")\n",
    "def update_polar_plot(selected_cluster, selected_clusterer, selected_state, selected_n_locales, selected_min_pop, selected_seeds):\n",
    "    df_out = recalculate_locales(df=df, bounds_df=bounds_df, state=selected_state, \n",
    "                                 n_locales=selected_n_locales, max_len=50000, eps_value=.25,\n",
    "                                 min_samples=30, min_pop=selected_min_pop, dbscan_x_include=selected_seeds)\n",
    "\n",
    "    cluster_df = df_out[df_out[selected_clusterer] == selected_cluster].sort_values(by='pop', ascending=False)\n",
    "\n",
    "    centroid_lat = cluster_df['lat'].mean()\n",
    "    centroid_lon = cluster_df['lon'].mean()\n",
    "    centroid_coords = (centroid_lat, centroid_lon)\n",
    "\n",
    "    cluster_df['theta'] = np.arctan2(cluster_df['lat'] - centroid_lat, cluster_df['lon'] - centroid_lon) * (180 / np.pi)\n",
    "    cluster_df['r'] = cluster_df['lat'].map(lambda lat: geodesic(centroid_coords, (lat, cluster_df.loc[cluster_df['lat'] == lat, 'lon'].values[0])).miles)\n",
    "    cluster_df.sort_values(by='pop', ascending=False, inplace=True)\n",
    "    fig_polar = px.scatter_polar(cluster_df,\n",
    "                                 r='r', theta='theta', hover_data=['pop'],\n",
    "                                 title=f\"Cluster {selected_cluster} Distribution\", color='pop', size='pop', width=1920*.8, height=1080*.8, template='plotly_dark',\n",
    "                                 color_continuous_scale=px.colors.sequential.Jet)\n",
    "\n",
    "    return fig_polar\n",
    "\n",
    "app.run(jupyter_model='external')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
